### ISSUE TITLE
The purpose of the repo

### ISSUE THREAD

**Issue by shunkakinoki** [papercups-io/chat-window#1]
Hi, thanks for the awesome project 🔥🔥🔥
You guys are really awesome!!! 
Best open source I've come across recently!

I know that this repo is still in WIP status, but was too tempted to know about what features this repo will bring!

Does this `chat-window` library make possible for implementing window-based integration of papercups-io?
ex) dedicated help window

**Comment by reichert621** [comment]
hey @shunkakinoki! for now the main purpose of this is allowing us to embed the chat window in an iframe (see this PR: https://github.com/papercups-io/chat-widget/pull/18)

but in the future, it should allow people to set up a dedicated help window, or embed a chat window wherever they like :)

**Comment by shunkakinoki** [comment]
@reichert621  Thanks for the reply!
The ability to embed an iframe would be very awesome!
I really appreciate the work, thanks so much!
